{{- if .Values.apiKeySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
data:
  apiKey: {{ .Values.apiKeySecret.apiKey | b64enc }}
{{- end}}
